require:
  - 'rubocop-performance'
  - 'rubocop-rspec'

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/BlockLength:
  Max: 200

Metrics/AbcSize:
  Max: 25

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Max: 20

RSpec/NoExpectationExample:
  Enabled: false
