require:
  - 'rubocop-performance'
  - 'rubocop-rspec'

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
