version: '3.9'

services:
  redis:
    image: redis
    restart: always
  api:
    build: .
    command: bash -c 'bundle exec puma'
    environment:
      - API_KEY=W4N1RHYjQihr5CMPWjYJIYImaxKySneA
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1
    volumes:
      - .:/weather_api
    ports:
      - '9292:9292'
    depends_on:
      - redis
