weather_data_service:
  api_key: <%= ENV['API_KEY'] %>
  city_id: 294021
  current_data_uri: 'https://dataservice.accuweather.com/currentconditions/v1/%i'
  historical_data_uri: 'https://dataservice.accuweather.com/currentconditions/v1/%i/historical/24'

cache_service:
  redis:
    host: <%= ENV.fetch('REDIS_HOST', 'localhost') %>
    port: <%= ENV.fetch('REDIS_PORT', 6379) %>
    db: <%= ENV.fetch('REDIS_DB', 1) %>
  ttl: 3600 # seconds
  key_prefix: 'weather_api_cache:%s'
